config/routes.rb
Rails.application.routes.draw do
  resources :categories, only:[:new, :create, :index]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :transactions, only: [:new, :create, :index]
  resources :groups, only:[:new, :create, :index] do
    resources :transactions, only:[:new, :create, :index]
  end
  root "groups#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :transactions, through: :transaction_categories

  validates :name, presence: true
end

app/models/category_transaction.rb
class CategoriesTransaction < ApplicationRecord
  belongs_to :transaction
  belongs_to :category
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true
  validates :icon, presence: true

  belongs_to :user
  has_many :transactions, dependent: :destroy
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  validates :name, presence: true
  validates :amount, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :user_id, presence: true
  validates_presence_of :category_ids

  belongs_to :user
  belongs_to :group
  has_and_belongs_to_many :categories
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin], multiple: false) ##
  ############################################################################################

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups
  has_many :transactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.where(user_id: current_user.id).order(created_at: :desc)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.user_id = current_user.id
    if @category.save
      redirect_to categories_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :user_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  access user: :all, admin: :all

  def index
    @groups = Group.joins(:user).where(users: { id: current_user.id })
    @group_sums = Transaction.where(group_id: @groups.pluck(:id)).group(:group_id).sum(:amount)
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id
    if @group.save
      redirect_to groups_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def group_params
    params.require(:group).permit(:name, :icon, :user_id)
  end
end

app/controllers/transaction_controller.rb
class TransactionController < ApplicationController
  
  def index
    @transactions = Transaction.all
  end

  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.user_id = current_user.id
    if @transaction.save
      redirect_to transactions_path
    else
      render "new", status: :unprocessable_entity
    end
  end

  def transaction_params
    params.require(:transaction).permit(:name, :amount, :user_id)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  access user: :all, admin: :all

  def index
    @group = Group.find(params[:group_id])
    @transactions = Transaction.where(group_id: @group.id, user_id: current_user.id).order(created_at: :desc)
    @transactions_sum = @transactions.sum(:amount)
  end

  def new
    @transaction = Transaction.new
    @categories = Category.where(user_id: current_user.id)
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.user_id = current_user.id
    if @transaction.save
      redirect_to group_transactions_path(@transaction.group_id)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  private

  def transaction_params
    params.require(:transaction).permit(:name, :amount, :user_id, :group_id, category_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/views/categories/_form.html.erb
<div class="mt-2 sm:mt-0 max-w-screen-lg px-4 py-8 mx-auto">
  <div class="md:grid md:grid-cols-3 md:gap-6">
    <div class="mt-5 md:col-span-2 md:mt-0">
    <h1 class="pl-5 text-lg">Create a New Category</h1>
      <%= form_with scope: :category, url: categories_path, local: true do |form| %>
      <% if @category.errors.any? %>
            <% @category.errors.full_messages.each do |message|%>
                <h3 class="text-red-700"><%= message %> </h3>
            <%end%>
          <%end%>
        <div class="overflow-hidden shadow sm:rounded-md">
          <div class="bg-white px-4 py-5 sm:p-6">
            <div class="grid grid-cols-6 gap-6">
              <div class="col-span-6 sm:col-span-3">
                <label for="first-name" class="block text-sm font-medium text-gray-700">name</label>
                <%= form.text_field :name, class: "mt-1 block w-full border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
              </div>
            </div>
          </div>
          <div class="bg-gray-50 px-4 py-3 text-right sm:px-6">
            <%= form.submit "Create Transaction", class: "inline-flex justify-center border border-transparent cursor-pointer bg-secondColor py-2 px-4 text-sm font-medium text-white shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<div class="flex h-full flex-col overflow-y-scroll bg-white shadow-xl  max-w-screen-lg px-4 py-2 mx-auto">
  <div class="flex-1 overflow-y-auto py-2 px-4 sm:px-6">
    <div class="flex items-start justify-between">
      <h2 class="text-lg font-medium text-gray-900" id="slide-over-title">List of all your categories</h2>
    </div>

    <div class="mt-8">
      <div class="flow-root">
        <ul role="list" class="-my-6 divide-y divide-gray-200">
          <% @categories.each do |category| %>
            <li class="flex py-6">

              <div class="ml-4 flex flex-1 flex-col">
                <div>
                  <div class="flex justify-between text-base font-medium text-gray-900">
                    <div>
                      <h3><%= category.name %> </h3>
                      <span class="text-gray-500 text-sm">created on <%= category.created_at.strftime("%B %e, %Y")%> </span>
                    </div>
                  </div>
                </div>
              </div>

            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="py-6 px-4 sm:px-6">
      <div class="mt-6">
        <%= link_to 'Create Category', new_category_path, class: "flex items-center justify-center border border-transparent bg-secondColor px-6 py-3 text-base font-medium text-white shadow-sm" %>
      </div>
    </div>

  </div>        
</div>

app/views/categories/new.html.erb
<%= render "form", group: @category %>

app/views/groups/_form.html.erb
<div class="mt-10 sm:mt-0 max-w-screen-lg px-4 py-8 mx-auto">
  <div class="md:grid md:grid-cols-3 md:gap-6">
    <div class="mt-5 md:col-span-2 md:mt-0">
    <h1 class="pl-5 text-lg">Create a New Group</h1>
      <%= form_with(model: group) do |form| %>
        <div class="overflow-hidden shadow sm:rounded-md">
          <div class="bg-white px-4 py-5 sm:p-6">
            <% if @group.errors.any? %>
              <% @group.errors.full_messages.each do |message|%>
                  <h3 class="text-red-700"><%= message %> </h3>
              <%end%>
            <%end%>
            <div class="grid grid-cols-6 gap-6">
              <div class="col-span-6 sm:col-span-3">
                <label for="first-name" class="block text-sm font-medium text-gray-700">name</label>
                <%= form.text_field :name, class: "mt-1 block w-full border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
              </div>

              <div class="col-span-6 sm:col-span-3">
                <label for="last-name" class="block text-sm font-medium text-gray-700">Icon Link</label>
                <%= form.text_field :icon, class: "mt-1 block w-full border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
              </div>
          </div>
          <div class="bg-gray-50 px-4 py-3 text-right sm:px-6">
            <%= form.submit "Create Group", class: "inline-flex justify-center border border-transparent bg-secondColor py-2 px-4 text-sm font-medium text-white shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 cursor-pointer" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="flex h-full flex-col overflow-y-scroll bg-white shadow-xl  max-w-screen-lg px-4 py-2 mx-auto">
  <div class="flex-1 overflow-y-auto py-2 px-4 sm:px-6">
    <div class="flex items-start justify-between">
      <h2 class="text-lg font-medium text-gray-900" id="slide-over-title">Groups</h2>
      <%= link_to "New Category", categories_path, class: "inline-flex justify-center border border-transparent cursor-pointer bg-secondColor py-2 px-4 text-sm font-medium text-white shadow-sm focus:outline-none focus:ring-2 focus:ring-secondColor focus:ring-offset-2"%>
    </div>

    <div class="mt-8">
      <div class="flow-root">
        <ul role="list" class="-my-6 divide-y divide-gray-200">
          <% @groups.each do |group| %>
            <li class="flex py-6">
              <div class="h-24 w-24 flex-shrink-0 overflow-hidden rounded-md border border-gray-200">
                <%= image_tag group.icon, class: "h-full w-full object-cover object-center" %>
              </div>

              <div class="ml-4 flex flex-1 flex-col">
                <div>
                  <div class="flex justify-between text-base font-medium text-gray-900">
                    <h3>
                      <%= link_to group.name, group_transactions_path(group_id: group.id) %>
                    </h3>
                    <p class="ml-4">
                      <span class="font-bold">Total Amount:</span> <%= @group_sums[group.id] || 0 %> $
                    </p>
                  </div>
                </div>
                <div class="flex flex-1 items-end justify-between text-sm">
                  <p class="text-gray-500">
                    <span>Created</span> <%= time_ago_in_words(group.created_at) %> ago
                  </p>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="py-6 px-4 sm:px-6 fixed bottom-0 left-0 right-0 mb-6 ml-6">
      <div class="mt-6">
        <%= link_to 'Create Group', new_group_path,  class: "flex items-center justify-center border border-transparent bg-secondColor px-6 py-3 text-base font-medium text-white shadow-sm" %>
      </div>
    </div>

  </div>        
</div>

app/views/groups/new.html.erb
<%= render "form", group: @group %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%=render 'shared/nav'%>

    <p class="mx-auto max-w-4xl py-3 px-3"> 
      <span class= "text-green-600"><%= notice  %></span>
      <span class= "text-green-600" ><%= alert %> </span>
    </p>

    <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
<% if user_signed_in? %>
    <nav class="bg-bluenav">
        <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
            <div class="relative flex h-16 items-center justify-between">
                <div class="absolute inset-y-0 left-0 flex items-center">
                    <!-- Mobile menu button-->
                    <button type="button" class="inline-flex items-center justify-center rounded-md p-2 text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
                        <%= link_to "Go Back", root_path %>
                    </button>
                </div>
                <div class="flex flex-1 items-center justify-center sm:items-stretch  ">
                    <div class="flex flex-shrink-0 items-center">
                    <a href="/" class = "text-white ">Budget Buddy</a>
                    </div>
                </div>
                <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">

                    <!-- logout -->
                    <div class="relative ml-3">
                        <div>
                            <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "bg-transparent text-white font-semibold py-1 px-2 border border-white" %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>

<% end %>

app/views/transactions/_form.html.erb
<div class="mt-10 sm:mt-0 max-w-screen-lg px-4 py-8 mx-auto">
  <div class="md:grid md:grid-cols-3 md:gap-6">
    <div class="mt-5 md:col-span-2 md:mt-0">
    <h1 class="pl-5 text-lg">Create New Transaction</h1>
      <%= form_with model: @transaction do |form| %>
        <div class="overflow-hidden shadow sm:rounded-md">
          <div class="bg-white px-4 py-5 sm:p-6">
          <% if @transaction.errors.any? %>
            <% @transaction.errors.full_messages.each do |message|%>
                <h3 class="text-red-700"><%= message %> </h3>
            <%end%>
          <%end%>
            <div class="grid grid-cols-6 gap-6">
              <div class="col-span-6 sm:col-span-3">
                <label for="first-name" class="block text-sm font-medium text-gray-700">name</label>
                <%= form.text_field :name, class: "mt-1 block w-full border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
              </div>

              <div class="col-span-6 sm:col-span-3">
                <label for="last-name" class="block text-sm font-medium text-gray-700">Amount</label>
                <%= form.text_field :amount, class: "mt-1 block w-full border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
              </div>

              <div class="col-span-6 sm:col-span-3">
                <label for="category" class="block text-sm font-medium text-gray-700">Category</label>
                <%# <%= form.select :category_ids, options_for_select(@categories.collect {|c| [ c.name, c.id ] }), {}, {multiple: true, class: "mt-1 block w-full border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"} %> 
                <% if !@categories.blank? %>
                  <%= form.select :category_ids, options_for_select(@categories.collect {|c| [ c.name, c.id ] }), {}, {multiple: true, class: "mt-1 block w-full border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"} %>
                <% else %>
                  <p class="text-red-600"> ⚠️ ⚠️ Refresh this page and make sure to select a category </p>
                <% end %>
              </div>

              <div class="col-span-6 sm:col-span-4 hidden">
                <label for="email-address" class="block text-sm font-medium text-gray-700">User ID</label>
                <%= form.text_field :user_id, :value => current_user.id %>
              </div>

              <div class="col-span-6 hidden">
                <label for="street-address" class="block text-sm font-medium text-gray-700">Group ID</label>
                <%= form.text_field :group_id, :value => params[:group_id] %> 
            </div>
          </div>
          <div class="bg-gray-50 px-4 py-3 text-right sm:px-6">
            <%= form.submit "Create Transaction", class: "inline-flex justify-center border border-transparent cursor-pointer bg-secondColor py-2 px-4 text-sm font-medium text-white shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/transactions/index.html.erb
<div class="flex h-full flex-col overflow-y-scroll bg-white shadow-xl  max-w-screen-lg px-4 py-2 mx-auto">
  <div class="relative flex-1 overflow-y-auto py-2 px-4 sm:px-6 h-64">
    <div class="flex items-start justify-between">
      <h2 class="text-lg font-medium text-gray-900" id="slide-over-title">Total Amount for group <%= @group.name %>: <%= @transactions_sum || 0 %> $</h2>
    </div>

    <div class="mt-8">
      <div class="flow-root">
        <ul role="list" class="-my-6 divide-y divide-gray-200">
          <% @transactions.each do |transaction| %>
            <li class="flex py-6">

              <div class="ml-4 flex flex-1 flex-col">
                <div>
                  <div class="flex justify-between text-base font-medium text-gray-900">
                    <div>
                      <h3><%= transaction.name %> </h3>
                      <span class="text-gray-500 text-sm">created on <%= transaction.created_at.strftime("%B %e, %Y")%> </span>
                    </div>
                    <p class="ml-4"><%= transaction.amount %> $</p>
                  </div>
                </div>
              </div>

            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="py-6 px-4 sm:px-6 fixed bottom-0 left-0 right-0 mb-6 ml-6">
      <div class="mt-6">
        <%= link_to 'Create transaction', new_group_transaction_path(group_id: @group.id), class: "flex items-center justify-center border border-transparent bg-secondColor px-6 py-3 text-base font-medium text-white shadow-sm" %>
      </div>
    </div>

  </div>        
</div>

app/views/transactions/new.html.erb
<%= render "form", transaction: @transaction %>